language: objective-c
xcode_project: JRAuditableEntityUI.xcodeproj
xcode_scheme: JRAuditableEntityUI
xcode_sdk: iphonesimulator9.3
before_install: gem install cocoapods slather -N
after_success:
- pod lib lint --quick
- slather
notifications:
  slack:
    secure: xMF0gyFbW58RqIbruZ99AKNRKZdlqKJZiSemsRB42MbeMYOPOZzdxwVQzIoc0k/AQanqQXFxRYL1cv/6XshNihmV3WOvDmloHhM0FK1iyUTG+bE8szjZQWNmPYOLgXArkGLOhky1mnwKnkza6ZGkKeMP1Y7Y85ddDxCwWxZDrRNk8vokjBvMSrqzitmQE9M0mSDaPNWsBo2c/fUctgkIx7jLMIy8f3/MdJqIM7dwVCXqsbIbyz/C3Fiu/3fw+n6CMZ8yKcpjzGVH1+b8FqnUGIHSkx7parAp1Xl/hyQJ+CmLAo4g4paKTVp0hbIzq4KNweNQyZiIhUfC7M4ow4AjwOvwY5Kfao9exWpv/pVmjpDJaXxXrOEF5qbrC/8FL+tN8bPPbym8wxXuBRcyg52Q0gzaLNI6GS1a5qo6XX6HIUxBucclI5R1ZHA1B0BkKyRfPwDpC6e/5QEliIC2cz5zwCRPM5Epi588Wr3GAyWHSsGEUS6sxplAxEbvP0PNXU+bGAkgOOHNE/iv3SDUc/jBz+LswmHedbOxNeVEho+rUeBIATCO8wUmMaFrGcHZz6oc71FWL/e+7oDsaDO7nTnyQZnQWXcYC3Aikp6G6VhjfzylZmmg9ZU80kChp3h6hwy5b5wbC43Mx4bJ1Vm4MP0K0aBwkCAJPhqY+7UauqQht4I=
